### ISSUE TITLE
Feature: Add user config file

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#102]
Add a yaml or json config file to allow a user to customize the git log arguments

Add configs for
* git log arguments
* theme color (?) -- Currently enabled, no mention of it, we shuold set it...
Users may not want a standard git log, maybe a config file could accept arguments in an array and inject them into the `git log` command on [space].

Should probably accept git arguments split in an array for now. ie:
`['--stat', '--pretty=oneline', '--max-count=20']`

Consider looking at https://github.com/lorenwest/node-config per @excalith 's recommendations

Edit: Expand this ticket to cover not just git log arguments, but also identify other areas of opportunity to create configurable options for the user.

**Comment by jwu910** [comment]
Maybe change the direction of this ticket to have CIO look for a config file somewhere in like `~/.config` or `~/.cio` or `~/.check-it-out`

**Comment by excalith** [comment]
Hey there,
Tried something related to cross platform config file and had promising results. Instead of node-config, I used configstore which seems to be the fastest way to implement config. 

So, If client runs the app for the first time, it creates a json file in ~/.config/configstore/check-it-out.json, and app.js reads values from json file. If you pass --settings argument, it opens the json file with default editor to edit settings within. In order to use more settings, we might need to create settings class within utils to ease the pain.

So far only log alias works, I couldn't manage to pass theme color within to interface.js from app.js. There are still a few tweaks required, but you can check it out https://github.com/excalith/check-it-out/tree/CIO-102-config-support before PR to see if I am in the right direction.

**Comment by jwu910** [comment]
Hey @excalith I skimmed through your commit and it looks like there are more changes than there should be. Did some of the build files make it into the source?

**Comment by excalith** [comment]
Hey @jwu910 I only changed the following files:
* package.json: added opn & configstore
* src/app.js: seems like my ide formatted the file, will fix that to show only settings related changes
* src/utils/helpText.js: added --settings information

**Comment by jwu910** [comment]
@excalith I think the formatting changes are fine. I use prettier and eslint(though I might have conflicting styles for arrays).

The extra changes I saw looked like transpired JS in app.js. The src files should be in es6.

Feel free to open a PR and I can review there too.
